name: Manual Deploy to Papaki

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Papaki via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          protocol: ftp
          local-dir: ./
          server-dir: ${{ secrets.DIR }}
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.md
